### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by kai-soul** [THOSE-EYES/PDF-Text-Changer#1]
can you give an command line example?
I try so many times but it give the error
![image](https://user-images.githubusercontent.com/81071306/120894566-b23b2700-c64b-11eb-84e8-6283a5149e0e.png)

**Comment by THOSE-EYES** [comment]
@kai-soul replacements should be JSON-like : { "a":"b"}.

**Comment by kai-soul** [comment]
> @kai-soul replacements should be JSON-like : { "a":"b"}.

![image](https://user-images.githubusercontent.com/81071306/120895313-efed7f00-c64e-11eb-9108-5308670523da.png)
like this?

**Comment by kai-soul** [comment]
oh, I understand, thank you very much!
