### ISSUE TITLE
Problem with input file

### ISSUE THREAD

**Issue by toniojst** [THOSE-EYES/PDF-Text-Changer#2]
Hi i get problem with input file. I always get error that file is not specified, but as you see the file is there and also path to python script working from attached printscreen. what i do wrong?

![SharedScreenshot](https://user-images.githubusercontent.com/8342958/141696786-4cb5e0fa-9ad9-4b4a-b257-b33c14c959d6.jpg)

**Comment by THOSE-EYES** [comment]
The problem is that the script can't find your file and that's all. Also, you don't have to write "<" and ">" in the JSON parameter.
