### ISSUE TITLE
Please help - AttributeError: 'ArrayObject' object has no attribute 'getData'

### ISSUE THREAD

**Issue by fire17** [THOSE-EYES/PDF-Text-Changer#3]
Hi there ! this looks really cool :)
Could you please share the dependencies you're using ? which version of pypdf2 and python ?

Got this error message on both python3.8 and 2.7
```
Traceback (most recent call last):
  File "replacer.py", line 131, in <module>
    main()
  File "replacer.py", line 125, in main
    out = replacer.process()
  File "replacer.py", line 87, in process
    self.__processFile()
  File "replacer.py", line 73, in __processFile
    contents = self.__processContent(contents)
  File "replacer.py", line 43, in __processContent
    data = content.getData()
AttributeError: 'ArrayObject' object has no attribute 'getData'
```
please advise :pray: 

thanks and have a good one! :)

**Comment by THOSE-EYES** [comment]
Seems like there is a problem with the PyPDF library itself. I will try to figure out which version works and then will fix the issue with the project.

**Comment by THOSE-EYES** [comment]
@fire17 ,seems like it is working and actually depends on the PDF you are trying to change.
